version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7000:7000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: alvistack/postgres-12
    env_file:
      - .development.env
    environment:
      PG_DATA: /usr/local/var/postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/usr/local/var/postgres
    restart: always
volumes:
  pgdata:
